### ISSUE TITLE
Add Data Annotations to the Player class

### ISSUE THREAD

**Issue by Scyllizzy** [Scyllizzy/Uno#12]
## To Start:
**Player class:** 
(Research how long the names, emails, and usernames should be)
- FirstName should be limited in size
- LastName should be limited in size
- Username should be limited in size
- The email shouldn't be too long either
- Win should be >= 0
- Loss should be >= 0

**Comment by TheRealRobertShields** [comment]
Do we want a Password property? @Scyllizzy @Reese2596

**Comment by Reese2596** [comment]
I didn’t think it was necessary because we were just gonna play Uno. But if you like to add one it’s up to you.

**Comment by TheRealRobertShields** [comment]
I think it'd be ideal to add a Password property if not just for more programming experience.

**Comment by Reese2596** [comment]
Closed with PullRequest #17
