### ISSUE TITLE
Create Deck 

### ISSUE THREAD

**Issue by Reese2596** [Scyllizzy/Uno#18]
Four colors in deck plus the wilds are black
Deck of card containing (108 cards in total)
- 4 - wild cards
- 4 - Draw 4 wild cards
- 1 - 0 card by color
- 2 - (1-9) cards by color
- 2 - Skip cards by color
- 2 - Draw 2 cards by color
- 2 - Reverse cards by color

Hard coded into the project.

**Comment by Scyllizzy** [comment]
I'm assigning this to myself because I would like to complete this issue

**Comment by Reese2596** [comment]
Been done.
