### ISSUE TITLE
CRUD Forms Validation

### ISSUE THREAD

**Issue by TheRealRobertShields** [Scyllizzy/Uno#40]
Error messages update with each attempt and success message displays upon validation.

AddPlayerForm - Completed, 03/11/20
EditPlayerForm -
DeletePlayerForm - Completed, 03/11/20

**Comment by Scyllizzy** [comment]
Im not sure what exactly you are talking about. Can you elaborate?

**Comment by Reese2596** [comment]
He was saying to add messages conveying if the add person was successful or a failure. Right now when you add a player nothing happens so you don’t know if the player was added or not. So we want it to display when a player is added successfully instead of showing nothing.
