### ISSUE TITLE
Create Database for Players

### ISSUE THREAD

**Issue by Reese2596** [Scyllizzy/Uno#5]
Create the Database with validation client and server-side. 

**Add:** Player
**Update:** Player
**Delete:** Player
**View all Players:** via UserName or PlayerID

**Comment by TheRealRobertShields** [comment]
I'm looking into this. @Reese2596 @Scyllizzy

**Comment by TheRealRobertShields** [comment]
I have to make the PLAYER class public.

**Comment by Reese2596** [comment]
Do you want to fix the players class or I can update it in the branch I created for it?

**Comment by TheRealRobertShields** [comment]
I can fix it. I can push my changes to github if you want that way it'll be public for you too and you can have what I added so far. I created the GetAllPlayers and Add methods for the DB @Scyllizzy

**Comment by Reese2596** [comment]
Okay go ahead and do a pull request for the updates to the player class and dB. But don’t close the issue yet. We still have to create the DB.

**Comment by TheRealRobertShields** [comment]
I pushed what I have so far.
I made the Player class public and added a Password property.
then I made the DB with the GetAllPlayers(), Add(), Delete(), Update() methods.
I'll leave this issue open so you can review it first.

**Comment by Reese2596** [comment]
Okay did you actually create the database or make the context page because if you made the database the issue can be closed if not I’ll start on it around 2

**Comment by Reese2596** [comment]
I reviewed what you added and it seems you have already created the Database and the actions that need to be completed (Add, Delete, update, etc.) so you can merge it to the master class @TheRealRobertShields
